# The name of the workflow, which appears in the GitHub Actions UI.
name: CI

# Specifies the events that trigger this workflow.
on:
  # Trigger the workflow on push events to the main branch.
  push:
    branches:
      - main
  # Trigger the workflow on pull request events targeting the main branch.
  pull_request:
    branches:
      - main

# Defines the jobs to run as part of this workflow.
jobs:
  # A job named 'build'.
  build:
    # Specifies the type of machine to run this job on.
    runs-on: ubuntu-latest

    # The steps to run as part of this job.
    steps:
      # Checks out the repository's code so the job can access it.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Sets up Node.js on the runner machine.
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Installs the project dependencies.
      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=navtajr_FHB-Assignment-Backend
            -Dsonar.organization=navtajr

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/noteapp:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/noteapp:${{ github.sha }}